
version: "3.9"
services:
  canaryshop:
    build: ../app/canaryshop
    ports:
      - "127.0.0.1:8088:8080"
    environment:
      - LOG_PATH=/logs/canaryshop.log
    volumes:
      - ../data:/data
      - ../data/logs:/logs
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "127.0.0.1:9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 30
  dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      - OPENSEARCH_HOSTS=['http://opensearch:9200']
    depends_on:
      - opensearch
